version: '2.2'
# docker run --name es01 --net elastic -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -e "xpack.security.enabled=false" -t docker.elastic.co/elasticsearch/elasticsearch:8.11.1
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx2048m
    volumes:
      - ./es_data:/usr/share/elasticsearch/data/
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
    healthcheck:
      test:     
        [
          "CMD-SHELL",
          "curl -s --user elastic:${ELASTIC_PASSWORD} -X GET http://localhost:9200/_cluster/health?pretty | grep status | grep -q '\\(green\\|yellow\\)'"
        ]
      interval: 10s
      timeout: 10s
      retries: 24

# docker run --name kib01 --net elastic -e "ELASTICSEARCH_HOSTS=http://es01:9200" -p 5601:5601 docker.elastic.co/kibana/kibana:8.11.1
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy

#  docker run --rm --name logstash_clickstream_load --net elk_demo_elastic -v ${PWD}/logstash/:/app -it logstash:8.11.1 logstash -f /app/clickstream.conf
#  logstash:
#    image: docker.elastic.co/logstash/logstash:8.11.1
#    container_name: logstash
#    networks:
#      - elastic
#    volumes:
#      - ./logstash:/app
#      - ./logstash/clickstream.conf:/usr/share/logstash/config/logstash.conf
#    depends_on:
#      elasticsearch:
#        condition: service_healthy


      
networks:
  elastic:
    driver: bridge
